import type { Metadata } from "next";
import { geistSans, geistMono } from "./fonts/fonts"; // Import fonts from the new file
import "./globals.css";

import Header from "./Components/Header";
import Footer from "./Components/Footer";
import Head from "next/head";

export const metadata: Metadata = {
  title: "UI-UX HACKATHON3-TEMPLATE 0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main className="container mx-auto px-4 sm:px-6 lg:px-8">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
